name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9.18, 3.10.13, 3.11.7, 3.12.1]

    steps:
    - uses: actions/checkout@v4
    - name: Install uv and set the python version
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.5.18"
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: make install 
    - name: Check Python package
      run: uv run poe check
